name: Python CI

on:
  [push]

env:
  AZURE_WEBAPP_NAME: toyscriptapi # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'backend' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: make web folder
      run: |
        mkdir ./backend/web
        
    - name: npm install, build
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        cd frontend
        npm install
        npm run build --if-present
      working-directory: my-app-path
    - name: Install dependencies
      run: |
        cd ../backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: move build files 
      run: |
        rm -rf ./static
        mv -f ../frontend/build ./static
    - name: Building web app
      uses: azure/appservice-build@v2
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
